#include "Assets.h"
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string_view>
#include <vector>
#include "Platform.h"

namespace LonelyIce
{
    struct AssetEntry
    {
        char const* path;
        unsigned char const* data;
        std::size_t const& size;
    };

    // Generated by CMake from assets/ (AssetIndex.cpp and one array per file).
    extern AssetEntry const g_assetIndex[];
    extern std::size_t const g_assetCount;
}

namespace
{
    struct OpenAsset
    {
        std::vector<char> owned;
        char const* data = nullptr;
        std::size_t size = 0;
        std::size_t pos = 0;
    };

    std::string Normalize(std::string path)
    {
        for (char& c : path)
            if (c == '\\')
                c = '/';
        while (!path.empty() && path.front() == '/')
            path.erase(0, 1);
        return path;
    }

    std::string DiskRoot()
    {
        std::string const dir = LonelyIce::Platform::GetEnv("LONELYICE_ASSETS").value_or("");
        return dir.empty() ? std::string() : Normalize(dir) + "/";
    }
}

bool LonelyIce::ReadAsset(std::string const& rawPath, std::string& out)
{
    std::string const path = Normalize(rawPath);
    if (std::string const root = DiskRoot(); !root.empty())
    {
        std::ifstream f(root + path, std::ios::binary);
        if (f)
        {
            out.assign(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
            return true;
        }
    }
    for (std::size_t i = 0; i < g_assetCount; ++i)
    {
        if (path != g_assetIndex[i].path)
            continue;
        out.assign(reinterpret_cast<char const*>(g_assetIndex[i].data), g_assetIndex[i].size);
        return true;
    }
    return false;
}

std::vector<std::string> LonelyIce::ListAssets(std::string_view folder)
{
    std::vector<std::string> out;
    if (std::string const root = DiskRoot(); !root.empty())
    {
        std::error_code ec;
        for (auto const& e : std::filesystem::directory_iterator(root + std::string(folder), ec))
            if (e.is_regular_file(ec))
                out.push_back(std::string(folder) + e.path().filename().string());
    }
    if (out.empty())
        for (std::size_t i = 0; i < g_assetCount; ++i)
        {
            std::string_view const p = g_assetIndex[i].path;
            if (p.substr(0, folder.size()) == folder && p.find('/', folder.size()) == std::string_view::npos)
                out.emplace_back(p);
        }
    std::sort(out.begin(), out.end());
    return out;
}

LonelyIce::AssetFileInterface::AssetFileInterface()
{
    _diskRoot = DiskRoot();
}

Rml::FileHandle LonelyIce::AssetFileInterface::Open(Rml::String const& rawPath)
{
    std::string path = Normalize(rawPath);

    if (!_diskRoot.empty())
    {
        std::ifstream f(_diskRoot + path, std::ios::binary);
        if (f)
        {
            auto* a = new OpenAsset();
            a->owned.assign(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
            a->data = a->owned.data();
            a->size = a->owned.size();
            return reinterpret_cast<Rml::FileHandle>(a);
        }
    }

    for (std::size_t i = 0; i < g_assetCount; ++i)
    {
        if (path != g_assetIndex[i].path)
            continue;

        auto* a = new OpenAsset();
        a->data = reinterpret_cast<char const*>(g_assetIndex[i].data);
        a->size = g_assetIndex[i].size;
        return reinterpret_cast<Rml::FileHandle>(a);
    }

    return 0;
}

void LonelyIce::AssetFileInterface::Close(Rml::FileHandle file)
{
    delete reinterpret_cast<OpenAsset*>(file);
}

size_t LonelyIce::AssetFileInterface::Read(void* buffer, size_t size, Rml::FileHandle file)
{
    auto* a = reinterpret_cast<OpenAsset*>(file);
    size_t n = std::min(size, a->size - a->pos);
    std::memcpy(buffer, a->data + a->pos, n);
    a->pos += n;
    return n;
}

bool LonelyIce::AssetFileInterface::Seek(Rml::FileHandle file, long offset, int origin)
{
    auto* a = reinterpret_cast<OpenAsset*>(file);
    long base = origin == SEEK_SET ? 0 : origin == SEEK_CUR ? long(a->pos) : long(a->size);
    long target = base + offset;
    if (target < 0 || size_t(target) > a->size)
        return false;
    a->pos = size_t(target);
    return true;
}

size_t LonelyIce::AssetFileInterface::Tell(Rml::FileHandle file)
{
    return reinterpret_cast<OpenAsset*>(file)->pos;
}

size_t LonelyIce::AssetFileInterface::Length(Rml::FileHandle file)
{
    return reinterpret_cast<OpenAsset*>(file)->size;
}
